general cleanup: strip sh extension, strip 'echos', cleanup messages

diff --git a/portz_install b/portz_install
--- a/portz_install
+++ b/portz_install
@@ -16,24 +16,28 @@ portz_root=$PWD
 
 . ${portz_root}/portz_common.sh
 
+inform "prefix = $prefix"
+
 #set -x
 
 if [ "$1" = "--update" ] ; then
-    echo "$PNAME: updating repository"
+    inform "updating repository"
     exit 0
 elif [ "$1" = "--install" ] ; then
     shift
 else
-    echo "$PNAME: bad usage"
+    #fail "bad usage"
+    #exit 1
+    :
 fi
 
 packages=$*
 
 while [ -n "$packages" ] ; do
     for package in $packages ; do
-        echo "$PNAME: trying $package ..."
+        inform "trying $package ..."
         if portz_is_installed $package ; then
-            echo "$PNAME: $package already installed"
+            inform "already installed"
         elif portz_check_deps $package ; then
             portz_install $package        
         else
